Fix reference updated concurrently error for the filesystem storer
go-git/go-git pull request #1116
Opened 2024-06-18 08:47 UTC by Javier-varez

If a reference exists in the packed refs file but not in the actual refs folder, we need to fall back to reading the pack refs file when storing the reference.

This happens because by the time we are storing the reference, we open the file with write permissions and read from it. At that point, if the file is empty, we still need to read the valid reference. Otherwise, it will read 0, and assume that the references do not match (because the old value was read from the packed file).

Relates to https://github.com/go-git/go-git/issues/37

2024-06-28 21:50 UTC, pjbgf requested changes
@Javier-varez nice stuff! Thanks for looking into this issue. Apart from the nits below this LGTM.

2024-06-28 21:50 UTC, pjbgf commented on storage/filesystem/dotgit/dotgit.go
> +	if err == emptyRefFileError {
```suggestion
	if errors.Is(err, ErrEmptyRefFile) {
```

2024-06-28 21:50 UTC, pjbgf commented on storage/filesystem/dotgit/dotgit.go
> +var emptyRefFileError = refError("The file is empty")
Please move this to the top together with the other errors.

```suggestion
var ErrEmptyRefFile = errors.New("ref file is empty")
```

2024-06-28 21:50 UTC, pjbgf commented on storage/filesystem/dotgit/dotgit.go
> +		return nil, emptyRefFileError
```suggestion
		return nil, ErrEmptyRefFile
```

2024-06-28 23:50 UTC, Javier-varez commented
> @Javier-varez nice stuff! Thanks for looking into this issue. Apart from the nits below this LGTM.

Thank you for reviewing the PR. I just addressed the comments 👍🏻

2024-06-29 21:33 UTC, pjbgf approved these changes
@Javier-varez thanks for working on this. :bow:

2024-06-29 21:33 UTC, merged