fix: support empty pushes
go-git/go-git pull request #1249
Opened 2024-12-16 09:57 UTC by iainjreid

This PR aims to fix #1014 by returning a new `ErrFlushPacketRecieved` error when an empty `recieve-pack` request is sent by an up-to-date git client. This error can then be gracefully handled in upstream code as required.

2024-12-18 23:20 UTC, pjbgf requested changes
Added some comments. For the empty push change can you please add some tests to confirm the new behaviour?

2024-12-18 23:20 UTC, pjbgf commented on plumbing/protocol/packp/updreq_decode.go
> +	}
This would also represent an empty `update-request` message, and due to that I am thinking we are better off reusing the existing `ErrEmpty`.

2024-12-18 23:20 UTC, pjbgf commented on plumbing/protocol/packp/updreq_decode.go
> +	d := &updReqDecoder{r: io.NopCloser(r), s: pktline.NewScanner(r)}
This is trickier, as in the existing behaviour the callee is responsible for closing the reader `r`, with this change this swifts to the caller. For breaking changes such as this, the commit/PR would have to target `v6-exp` instead.

2025-01-03 10:06 UTC, scabala commented on plumbing/protocol/packp/updreq_decode.go
> +	d := &updReqDecoder{r: io.NopCloser(r), s: pktline.NewScanner(r)}
I think this can be revert, right? So the fix for up-to-date git client could be fixed.

2025-01-03 10:07 UTC, scabala commented
As for test: simple operation of `git pull && git pull` is able to trigger this bug. Dunno how it could be implemented in tests but at least it's a starting point

2025-09-07 07:02 UTC, closed without merging