pumbling: packfile, resolve external reference delta
go-git/go-git pull request #392
Opened 2021-10-11 12:10 UTC by ga-paul-t

I don't really want to take any credit for this work. This solution is a carbon copy of what was proposed in https://github.com/go-git/go-git/pull/111

Would really appreciate some feedback

2021-11-01 23:28 UTC, mcuadros requested changes
can you provide a test?

2021-11-02 07:48 UTC, ga-paul-t commented
@mcuadros I am working on adding a test this week. Just reading through and understanding the Git pack file specification. Apologies for the delay

2021-11-02 22:00 UTC, ga-paul-t commented
@mcuadros I admit that I am struggling to write a test. I need to write a test where a packfile is a thin pack. Looking at the tests with regards to the packfile parser, they all pretty much use scenarios that clone existing Github repositories. As I have only encountered this issue with CodeCommit repositories, I can't follow that same pattern.

Would I need to construct a packfile manually? Or do you know if I can force this behaviour with a Github repository?

@bassofed wondering if you have any suggestions?

I really want this to be merged, as without it CodeCommit (or repositories that use thin packs) might not work

2021-11-08 16:38 UTC, bassofed commented
> @mcuadros I admit that I am struggling to write a test. I need to write a test where a packfile is a thin pack. Looking at the tests with regards to the packfile parser, they all pretty much use scenarios that clone existing Github repositories. As I have only encountered this issue with CodeCommit repositories, I can't follow that same pattern.
> 
> Would I need to construct a packfile manually? Or do you know if I can force this behaviour with a Github repository?
> 
> @bassofed wondering if you have any suggestions?
> 
> I really want this to be merged, as without it CodeCommit (or repositories that use thin packs) might not work

Sorry for the delay.
I had the same problem. I saw this behavior in several CodeCommit repositories but they are private so I can't post in a example.

I faced the issue for the fist time in Portainer; if the pull fails, some functionality of Portainer are not working (https://github.com/portainer/portainer/issues/5185)

2021-11-09 15:22 UTC, ga-paul-t commented
@mcuadros I have attempted to write my first test. I have tried to replicate this behaviour from a GitHub repository, but with no luck. As CodeCommit is a private service within AWS, there is no way to follow the same structure with the existing fixtures. As a middle ground, I have provided a packfile from a CodeCommit repository that triggers the issue with go-git without the proposed fix in this PR.

Interested in your feedback on this approach

2021-11-21 10:04 UTC, ga-paul-t commented
@mcuadros any chance you could take a look. Thanks.

2021-12-10 05:54 UTC, mcuadros commented
This approach is correct but you need to add the pack to the github.com/go-git/go-git-fixtures repository, where we host all the packfile fixtures, sorry about the delay. @ga-paul-t

2021-12-15 07:44 UTC, ga-paul-t commented
@mcuadros I am attempting to add the packfile to the github.com/go-git/go-git-fixtures. I noticed there is a file called data.go, that is generated using "esc -o data.go -pkg=fixtures data".

I assume I need to regenerate this file?

2021-12-15 08:50 UTC, ga-paul-t commented
@mcuadros I have raised a PR against `go-git-fixtures` repository as requested, https://github.com/go-git/go-git-fixtures/pull/4

Once merged. I will update the existing test to make use of this new fixture

2021-12-22 11:03 UTC, mcuadros commented
@ga-paul-t merged the go-git-fixtures PR

2021-12-22 18:00 UTC, ga-paul-t commented
> @ga-paul-t merged the go-git-fixtures PR

@mcuadros Could you tag the latest release in the go-git-fixtures repo. `go get github.com/go-git/go-git-fixtures/v4` doesn't pull down the test fixture change. Thanks.

2021-12-27 19:58 UTC, mcuadros commented
My bad, I just tagged v4.3.0, @ga-paul-t

2021-12-29 07:06 UTC, ga-paul-t commented
> My bad, I just tagged v4.3.0, @ga-paul-t

I'll update the PR later today

2021-12-29 19:42 UTC, ga-paul-t commented
@mcuadros apologies but I just realised that I missed adding the .idx packfile to the `go-git-fixtures` repository. I have just raised another PR. Please accept my apologies for missing this. Link to the PR: https://github.com/go-git/go-git-fixtures/pull/5

Could you also retag when this has been merged? Thanks.

2022-01-05 00:56 UTC, mcuadros commented
done

2022-01-05 06:56 UTC, ga-paul-t commented on .gitignore
> +.tmp/
I added this to prevent accidental committing of temporary test files

2022-01-05 06:57 UTC, ga-paul-t commented
@mcuadros that is now done. I have updated the PR to use the `go-git-fixtures` repo

2022-01-08 13:22 UTC, merged

2022-06-10 22:52 UTC, katehmd commented
Is there any timeline for releasing a new go-git version that will include this PR?

2022-08-03 10:26 UTC, HDYA commented
it seems cloning repo from Azure Devops still does not work, even after this is merged and go mod specifying it by git hash.
is this expected?
thanks