plumbing: resolve non-external delta references
go-git/go-git pull request #485
Opened 2022-03-15 17:09 UTC by ZauberNerd

In a self-contained pack file delta references might point to base
objects stored later in the file.
In this case we need to replace placeholders for external refs with the
actual base object and update the children references.

Fixes: #484

2022-04-30 22:04 UTC, mcuadros commented
Can you add a test for this?

2022-04-30 22:08 UTC, ZauberNerd commented
I have prepared a test fixture here: https://github.com/go-git/go-git-fixtures/pull/6  I guess that needs to be merged first before I can write a test here.

2022-06-03 21:44 UTC, ericzhill commented
I just ran into this problem today and can confirm this PR does fix the issue for me as well.

2022-06-12 14:37 UTC, abrander commented
I too can confirm that this PR solves an issue with current master.

Exhibit:

```go
git.PlainClone("/tmp/repo", true, &git.CloneOptions{
	URL: "https://github.com/influxdata/line-protocol",
	NoCheckout: true,
})
```

2022-10-03 17:08 UTC, kyparisisg commented
I am running to the same problem and it looks like this PR solves the it!
could you please consider merging it?

2022-12-02 11:07 UTC, qliklars commented
We have also run into this problem. Is there a reason for not merging the PR?

2022-12-02 12:51 UTC, pjbgf commented
It would be great if there were tests that could reproduce the error this fixes.

2022-12-02 13:12 UTC, per1234 commented
@pjbgf isn't there one here?: https://github.com/go-git/go-git-fixtures/pull/6

2022-12-02 18:04 UTC, ZauberNerd commented
@pjbgf yes, that is how I think I'll do the tests. But for that to happen, the fixture needs to be merged first: https://github.com/go-git/go-git/pull/485#issuecomment-1114061954
Otherwise please advise me how to proceed or do the change yourself. Maintainer edits are allowed on this PR.

2022-12-03 16:22 UTC, pjbgf commented
@ZauberNerd I had a look at this today and can confirm that using your test fixture (and one additional test), this behaviour is fixed and tested for regression.

Please add another test in `parser_test.go`, which is similar to `TestResolveExternalRefsInThinPack`, but refers to the new tag `delta-before-bash` you have created on https://github.com/go-git/go-git-fixtures/pull/6. 

Whilst the other PR is not merged you can add this to the `go.mod`:
```
// Temporary fix, waiting for https://github.com/go-git/go-git-fixtures/pull/6.
replace github.com/go-git/go-git-fixtures/v4 => github.com/ZauberNerd/go-git-fixtures/v4 v4.0.0-20220316085525-96d6741f0b44
```

That would allow for the tests to pass, and for a maintainer to quickly test the entire E2E of this PR.

Once the other PR is merged, the above will need to be removed and the `go-git-fixtures` dependency updated.

2023-01-04 11:37 UTC, oshoval commented
Hi, Thanks for this great PR
Is it possible please to advance it ?
We also have the problem without it with some of our repositories, which blocks parts of the automation
Thanks

2023-02-08 10:28 UTC, qliklars commented
We also have problems without it, so it would be great if it was merged.
Thanks!

2023-02-08 23:45 UTC, Deiz commented
Not to pile on too much, but is there anything blocking merge of this and https://github.com/go-git/go-git-fixtures/pull/6 which it depends on, @mcuadros @pjbgf?

Anecdotally, something appears to have shifted on GitLab's side but non-external delta references seem to be cropping up with vastly higher frequency in GitLab-hosted repositories. Our organization has hit them twice in the last week, and it'd be nice to not litter a bunch of replace directives around to take advantage of this fix. 🙂

2023-02-09 11:04 UTC, pjbgf commented
I can't speak on what is blocking the merge, as the changes looks good to me. However, I don't have write access on this repository nor any official saying on the matter.

I did merge these changes on a fork I use (back in December) and so far it seems to be working as intended. So you are probably better off forking the project, and cherry-picking it until it gets merged.

2023-02-10 07:13 UTC, becjon commented
> Not to pile on too much, but is there anything blocking merge of this and [go-git/go-git-fixtures#6](https://github.com/go-git/go-git-fixtures/pull/6) which it depends on, @mcuadros @pjbgf?
> 
> Anecdotally, something appears to have shifted on GitLab's side but non-external delta references seem to be cropping up with vastly higher frequency in GitLab-hosted repositories. Our organization has hit them twice in the last week, and it'd be nice to not litter a bunch of replace directives around to take advantage of this fix. 🙂

We also have the problems you describe in combination with GitLab.com

2023-03-05 16:02 UTC, pjbgf requested changes
@ZauberNerd can you please rebase and check the nits below.

2023-03-05 16:02 UTC, pjbgf commented on go.mod
> +replace github.com/go-git/go-git-fixtures/v4 => github.com/ZauberNerd/go-git-fixtures/v4 v4.3.2-0.20221206142533-16c45f9dbd0a
The other PR has been merged, please remove the `replace` and update the `go-git-fixtures` in the `require` section to:

```
github.com/go-git/go-git-fixtures/v4 v4.3.2-0.20230305113008-0c11038e723f
```

2023-03-05 16:07 UTC, pjbgf commented
> I don't have write access on this repository nor any official saying on the matter.

This has now changed, so I should be able to get this merged once it is rebased.

2023-03-22 06:53 UTC, oshoval commented
Gm, any chance this can be advanced please ?
Thanks

2023-03-23 18:50 UTC, ZauberNerd commented
@mcuadros @pjbgf sorry for the delay. I have rebased and updated the PR. Please take another look.

2023-04-11 18:07 UTC, pjbgf commented
The [current failure](https://github.com/go-git/go-git/actions/runs/4504167118/jobs/8211140251?pr=485) is not related to the change. I will fix that on a follow-up PR.

2023-04-11 18:08 UTC, pjbgf approved these changes
@ZauberNerd Thank you very much for working on this and following up with the rebase.

2023-04-11 18:08 UTC, merged

2023-04-13 06:30 UTC, oshoval commented
Thanks, this is awesome
Is a new release planned please ?

2023-04-17 11:26 UTC, pjbgf commented
@oshoval in the beginning of next month we should have another version cut.

2023-05-21 09:23 UTC, oshoval commented
Hi, it seems no new release yet ? can you please consider one ?
Thanks

2023-05-28 08:32 UTC, oshoval commented
@pjbgf 
Thanks 

FYI 
https://sonarcloud.io/project/security_hotspots?id=kubevirt_cluster-network-addons-operator&pullRequest=1561&resolved=false&types=SECURITY_HOTSPOT