Update commit graph code to allow for SHA256 commit-graphs
go-git/go-git pull request #853
Opened 2023-09-30 08:09 UTC by zeripath

Since the build-tag sha256 was introduced the commit graph code should be switched to use hash.Size and only use a graph if it has the correct hash version for the version of go-git that is built.

2023-09-30 08:27 UTC, pjbgf requested changes
@zeripath nice addition. Please reword the commit in line with the [contributing guide](https://github.com/go-git/go-git/blob/master/CONTRIBUTING.md#format-of-the-commit-message).

2023-09-30 08:27 UTC, pjbgf commented on plumbing/format/commitgraph/file.go
> +	offset := fi.commitDataOffset + int64(idx)*(hash.Size+16)
Let's move `16` to a constant.

2023-09-30 09:31 UTC, zeripath commented
OK done.

2023-09-30 09:47 UTC, zeripath commented
I have a lot more changes to make to the commit graph code - but some of them will need to change the signature of commit data - would that be ok or should I create a v2 package?

For example, the index within a graph file should be uint32 not an int.

2023-09-30 09:47 UTC, zeripath commented on plumbing/format/commitgraph/file.go
> +	offset := fi.commitDataOffset + int64(idx)*(hash.Size+16)
Done

2023-10-01 20:53 UTC, pjbgf commented
@zeripath merging this one as-is as it is mostly self-contained. Let's discuss the rest on the other PR.

> would that be ok or should I create a v2 package? For example, the index within a graph file should be uint32 not an int.

I would rather refrain from changing the API if possible. The support for SHA256 is blocked behind a build tag due to the amount of changes to support a different hash size without going through a shotgun surgery. But for `v6.0.0` we could think about the different API changes that it would require - maybe this could follow the same approach. But happy to consider other solutions as well.

For bouncing some ideas, feel free to reach out via [Slack](https://join.slack.com/t/go-git/shared_invite/zt-1tk7vwrsw-ywCUKRCo_uS_QbKMQ2ukpA).

2023-10-01 20:53 UTC, pjbgf approved these changes
@zeripath great job! :1st_place_medal:

2023-10-01 20:53 UTC, merged

2023-10-01 20:54 UTC, pjbgf commented
Relates to #229.